#!/bin/bash
pushd ~/Documents/git/r_packages
package=`cat ~/.tmp/targeted_r_package`
dunstify -r 1 -i "~/configs/dunst/r-project.svg" -t 2000 "Build" "Building package $package"
R CMD INSTALL --preclean --no-multiarch --with-keep.source $package
status=`echo $?`

case $status in
    0)
        dunstify -r 1 -i "~/configs/dunst/r-project.svg" -t 5000 "$package" "Build complete"
        ;;
    *)
        dunstify -r 1 -i "~/configs/dunst/r-project.svg" -t 7000 "Build" "Something went wrong!"
        ;;
esac

popd
