#!/bin/bash

setxkbmap -query | grep -q 'gr' && setxkbmap us || setxkbmap gr
current=$(setxkbmap -query | awk -F":" '{if ($1=="layout") {print $2}}')
dunstify -r 1 -i "/home/arekkas/configs/dunst/flag.png" -t 2000 "Language:${current}"

