#!/bin/bash

URL='https://google.com/search?q='
QUERY=$(echo '' | dmenu -p "Search google:")
if [ -n "$QUERY" ]; then
  qutebrowser "${URL}${QUERY}" 2> /dev/null
  # exec i3-msg [class="^Firefox$"] focus
fi
